// Mocks generated by Mockito 5.4.6 from annotations
// in cardio_tracker/test/infrastructure/services/sync_deduplication_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cardio_tracker/infrastructure/services/cloudflare_kv_service.dart'
    as _i2;
import 'package:cardio_tracker/infrastructure/services/manual_sync_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCloudflareKVService_0 extends _i1.SmartFake
    implements _i2.CloudflareKVService {
  _FakeCloudflareKVService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncResult_1 extends _i1.SmartFake implements _i3.SyncResult {
  _FakeSyncResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ManualSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockManualSyncService extends _i1.Mock implements _i3.ManualSyncService {
  @override
  _i2.CloudflareKVService get kvService => (super.noSuchMethod(
        Invocation.getter(#kvService),
        returnValue: _FakeCloudflareKVService_0(
          this,
          Invocation.getter(#kvService),
        ),
        returnValueForMissingStub: _FakeCloudflareKVService_0(
          this,
          Invocation.getter(#kvService),
        ),
      ) as _i2.CloudflareKVService);

  @override
  _i4.Future<_i3.SyncResult> performSync() => (super.noSuchMethod(
        Invocation.method(
          #performSync,
          [],
        ),
        returnValue: _i4.Future<_i3.SyncResult>.value(_FakeSyncResult_1(
          this,
          Invocation.method(
            #performSync,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.SyncResult>.value(_FakeSyncResult_1(
          this,
          Invocation.method(
            #performSync,
            [],
          ),
        )),
      ) as _i4.Future<_i3.SyncResult>);

  @override
  _i4.Future<bool> isSyncAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isSyncAvailable,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
