// Mocks generated by Mockito 5.4.6 from annotations
// in cardio_tracker/test/application/use_cases/get_all_readings_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cardio_tracker/core/errors/failures.dart' as _i5;
import 'package:cardio_tracker/domain/entities/blood_pressure_reading.dart'
    as _i6;
import 'package:cardio_tracker/domain/repositories/blood_pressure_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BloodPressureRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBloodPressureRepository extends _i1.Mock
    implements _i3.BloodPressureRepository {
  MockBloodPressureRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BloodPressureReading>>>
      getAllReadings() => (super.noSuchMethod(
            Invocation.method(
              #getAllReadings,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i6.BloodPressureReading>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.BloodPressureReading>>(
              this,
              Invocation.method(
                #getAllReadings,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.BloodPressureReading>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addReading(
          _i6.BloodPressureReading? reading) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReading,
          [reading],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addReading,
            [reading],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateReading(
          _i6.BloodPressureReading? reading) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReading,
          [reading],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateReading,
            [reading],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteReading(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteReading,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteReading,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BloodPressureReading>>>
      getReadingsByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getReadingsByDateRange,
              [
                startDate,
                endDate,
              ],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i6.BloodPressureReading>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.BloodPressureReading>>(
              this,
              Invocation.method(
                #getReadingsByDateRange,
                [
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.BloodPressureReading>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.BloodPressureReading?>>
      getLatestReading() => (super.noSuchMethod(
            Invocation.method(
              #getLatestReading,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i6.BloodPressureReading?>>.value(
                _FakeEither_0<_i5.Failure, _i6.BloodPressureReading?>(
              this,
              Invocation.method(
                #getLatestReading,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.BloodPressureReading?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BloodPressureReading>>>
      getRecentReadings({int? days = 30}) => (super.noSuchMethod(
            Invocation.method(
              #getRecentReadings,
              [],
              {#days: days},
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i6.BloodPressureReading>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.BloodPressureReading>>(
              this,
              Invocation.method(
                #getRecentReadings,
                [],
                {#days: days},
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.BloodPressureReading>>>);
}
