// Mocks generated by Mockito 5.4.6 from annotations
// in cardio_tracker/test/features/csv_editor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cardio_tracker/core/errors/failures.dart' as _i6;
import 'package:cardio_tracker/core/validators/reading_validator.dart' as _i10;
import 'package:cardio_tracker/domain/entities/blood_pressure_reading.dart'
    as _i7;
import 'package:cardio_tracker/domain/repositories/blood_pressure_repository.dart'
    as _i4;
import 'package:cardio_tracker/infrastructure/services/csv_export_service.dart'
    as _i8;
import 'package:cardio_tracker/infrastructure/services/csv_import_service.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCsvImportResult_1 extends _i1.SmartFake
    implements _i3.CsvImportResult {
  _FakeCsvImportResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BloodPressureRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBloodPressureRepository extends _i1.Mock
    implements _i4.BloodPressureRepository {
  MockBloodPressureRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.BloodPressureReading>>>
      getAllReadings() => (super.noSuchMethod(
            Invocation.method(
              #getAllReadings,
              [],
            ),
            returnValue: _i5.Future<
                    _i2
                    .Either<_i6.Failure, List<_i7.BloodPressureReading>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.BloodPressureReading>>(
              this,
              Invocation.method(
                #getAllReadings,
                [],
              ),
            )),
          ) as _i5
              .Future<_i2.Either<_i6.Failure, List<_i7.BloodPressureReading>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> addReading(
          _i7.BloodPressureReading? reading) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReading,
          [reading],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #addReading,
            [reading],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> updateReading(
          _i7.BloodPressureReading? reading) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReading,
          [reading],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #updateReading,
            [reading],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deleteReading(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteReading,
          [id],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteReading,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.BloodPressureReading>>>
      getReadingsByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getReadingsByDateRange,
              [
                startDate,
                endDate,
              ],
            ),
            returnValue: _i5.Future<
                    _i2
                    .Either<_i6.Failure, List<_i7.BloodPressureReading>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.BloodPressureReading>>(
              this,
              Invocation.method(
                #getReadingsByDateRange,
                [
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i5
              .Future<_i2.Either<_i6.Failure, List<_i7.BloodPressureReading>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.BloodPressureReading?>>
      getLatestReading() => (super.noSuchMethod(
            Invocation.method(
              #getLatestReading,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, _i7.BloodPressureReading?>>.value(
                _FakeEither_0<_i6.Failure, _i7.BloodPressureReading?>(
              this,
              Invocation.method(
                #getLatestReading,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i7.BloodPressureReading?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.BloodPressureReading>>>
      getRecentReadings({int? days = 30}) => (super.noSuchMethod(
            Invocation.method(
              #getRecentReadings,
              [],
              {#days: days},
            ),
            returnValue: _i5.Future<
                    _i2
                    .Either<_i6.Failure, List<_i7.BloodPressureReading>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.BloodPressureReading>>(
              this,
              Invocation.method(
                #getRecentReadings,
                [],
                {#days: days},
              ),
            )),
          ) as _i5
              .Future<_i2.Either<_i6.Failure, List<_i7.BloodPressureReading>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> clearAllReadings() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearAllReadings,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #clearAllReadings,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> rebuildDatabase() =>
      (super.noSuchMethod(
        Invocation.method(
          #rebuildDatabase,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #rebuildDatabase,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> batchInsertReadings(
          List<_i7.BloodPressureReading>? readings) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchInsertReadings,
          [readings],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #batchInsertReadings,
            [readings],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> replaceAllReadings(
          List<_i7.BloodPressureReading>? readings) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAllReadings,
          [readings],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #replaceAllReadings,
            [readings],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [CsvExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCsvExportService extends _i1.Mock implements _i8.CsvExportService {
  MockCsvExportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String exportAllReadings(List<_i7.BloodPressureReading>? readings) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAllReadings,
          [readings],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #exportAllReadings,
            [readings],
          ),
        ),
      ) as String);
}

/// A class which mocks [CsvImportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCsvImportService extends _i1.Mock implements _i3.CsvImportService {
  MockCsvImportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.CsvImportResult> importFromCsv(String? csvContent) =>
      (super.noSuchMethod(
        Invocation.method(
          #importFromCsv,
          [csvContent],
        ),
        returnValue:
            _i5.Future<_i3.CsvImportResult>.value(_FakeCsvImportResult_1(
          this,
          Invocation.method(
            #importFromCsv,
            [csvContent],
          ),
        )),
      ) as _i5.Future<_i3.CsvImportResult>);
}

/// A class which mocks [ReadingValidator].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadingValidator extends _i1.Mock implements _i10.ReadingValidator {
  MockReadingValidator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void validateSystolic(int? systolic) => super.noSuchMethod(
        Invocation.method(
          #validateSystolic,
          [systolic],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void validateDiastolic(int? diastolic) => super.noSuchMethod(
        Invocation.method(
          #validateDiastolic,
          [diastolic],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void validateHeartRate(int? heartRate) => super.noSuchMethod(
        Invocation.method(
          #validateHeartRate,
          [heartRate],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void validateSystolicDiastolic(
    int? systolic,
    int? diastolic,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #validateSystolicDiastolic,
          [
            systolic,
            diastolic,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void validateTimestamp(DateTime? timestamp) => super.noSuchMethod(
        Invocation.method(
          #validateTimestamp,
          [timestamp],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void validateNotes(String? notes) => super.noSuchMethod(
        Invocation.method(
          #validateNotes,
          [notes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void validateCompleteReading({
    required int? systolic,
    required int? diastolic,
    required int? heartRate,
    required DateTime? timestamp,
    String? notes,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #validateCompleteReading,
          [],
          {
            #systolic: systolic,
            #diastolic: diastolic,
            #heartRate: heartRate,
            #timestamp: timestamp,
            #notes: notes,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  String? checkHeartRateReasonableness(
    int? systolic,
    int? diastolic,
    int? heartRate,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #checkHeartRateReasonableness,
        [
          systolic,
          diastolic,
          heartRate,
        ],
      )) as String?);
}
