// Mocks generated by Mockito 5.4.6 from annotations
// in cardio_tracker/test/presentation/providers/blood_pressure_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cardio_tracker/application/use_cases/add_reading.dart' as _i9;
import 'package:cardio_tracker/application/use_cases/clear_all_readings.dart'
    as _i14;
import 'package:cardio_tracker/application/use_cases/delete_reading.dart'
    as _i11;
import 'package:cardio_tracker/application/use_cases/get_all_readings.dart'
    as _i4;
import 'package:cardio_tracker/application/use_cases/get_reading_statistics.dart'
    as _i12;
import 'package:cardio_tracker/application/use_cases/rebuild_database.dart'
    as _i15;
import 'package:cardio_tracker/application/use_cases/update_reading.dart'
    as _i10;
import 'package:cardio_tracker/core/errors/failures.dart' as _i6;
import 'package:cardio_tracker/core/usecases/usecase.dart' as _i8;
import 'package:cardio_tracker/domain/entities/blood_pressure_reading.dart'
    as _i7;
import 'package:cardio_tracker/domain/repositories/blood_pressure_repository.dart'
    as _i2;
import 'package:cardio_tracker/domain/value_objects/reading_statistics.dart'
    as _i13;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBloodPressureRepository_0 extends _i1.SmartFake
    implements _i2.BloodPressureRepository {
  _FakeBloodPressureRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAllReadings].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllReadings extends _i1.Mock implements _i4.GetAllReadings {
  MockGetAllReadings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BloodPressureRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeBloodPressureRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.BloodPressureRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.BloodPressureReading>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, List<_i7.BloodPressureReading>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.BloodPressureReading>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.BloodPressureReading>>>);
}

/// A class which mocks [AddReading].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddReading extends _i1.Mock implements _i9.AddReading {
  MockAddReading() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BloodPressureRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeBloodPressureRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.BloodPressureRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i7.BloodPressureReading? reading) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [reading],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [reading],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [UpdateReading].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateReading extends _i1.Mock implements _i10.UpdateReading {
  MockUpdateReading() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BloodPressureRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeBloodPressureRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.BloodPressureRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i7.BloodPressureReading? reading) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [reading],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [reading],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [DeleteReading].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteReading extends _i1.Mock implements _i11.DeleteReading {
  MockDeleteReading() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BloodPressureRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeBloodPressureRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.BloodPressureRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i11.DeleteReadingParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [GetReadingStatistics].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetReadingStatistics extends _i1.Mock
    implements _i12.GetReadingStatistics {
  MockGetReadingStatistics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BloodPressureRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeBloodPressureRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.BloodPressureRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i13.ReadingStatistics>> call(
          _i12.StatisticsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i13.ReadingStatistics>>.value(
                _FakeEither_1<_i6.Failure, _i13.ReadingStatistics>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i13.ReadingStatistics>>);
}

/// A class which mocks [ClearAllReadings].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearAllReadings extends _i1.Mock implements _i14.ClearAllReadings {
  MockClearAllReadings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BloodPressureRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeBloodPressureRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.BloodPressureRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [RebuildDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRebuildDatabase extends _i1.Mock implements _i15.RebuildDatabase {
  MockRebuildDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BloodPressureRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeBloodPressureRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.BloodPressureRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
