// Mocks generated by Mockito 5.4.6 from annotations
// in cardio_tracker/test/domain/repositories/user_settings_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cardio_tracker/core/errors/failures.dart' as _i5;
import 'package:cardio_tracker/domain/entities/user_settings.dart' as _i6;
import 'package:cardio_tracker/domain/repositories/user_settings_repository.dart'
    as _i3;
import 'package:cardio_tracker/domain/value_objects/blood_pressure_category.dart'
    as _i7;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserSettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSettingsRepository extends _i1.Mock
    implements _i3.UserSettingsRepository {
  MockUserSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserSettings>> getSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserSettings>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserSettings>(
          this,
          Invocation.method(
            #getSettings,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserSettings>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveSettings(
          _i6.UserSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [settings],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveSettings,
            [settings],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateNotificationSettings(
          bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotificationSettings,
          [enabled],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateNotificationSettings,
            [enabled],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateDataSharingSettings(
          bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDataSharingSettings,
          [enabled],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateDataSharingSettings,
            [enabled],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateMedicationTimes(
          List<String>? times) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMedicationTimes,
          [times],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateMedicationTimes,
            [times],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateReminderTimes(
          List<String>? times) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReminderTimes,
          [times],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateReminderTimes,
            [times],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateTargetCategories(
    _i7.BloodPressureCategory? minCategory,
    _i7.BloodPressureCategory? maxCategory,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTargetCategories,
          [
            minCategory,
            maxCategory,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateTargetCategories,
            [
              minCategory,
              maxCategory,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> resetSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #resetSettings,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #resetSettings,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> hasSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #hasSettings,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #hasSettings,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
